//
// Created by fredd on 27/03/2020.
//

#ifndef A2_INTERPRETER_CONFIG_H
#define A2_INTERPRETER_CONFIG_H

#define INST_NAME_LEN 7
#define INST_CAT_LEN 3
#define INST_TYP_LEN 4
#define INST_SIZE 16
#define STACK_SIZE 2000
#define HEAP_SIZE 65536
#define LOG_DISPLAY_TIME 0

#endif //A2_INTERPRETER_CONFIG_H
